waypoints:
    - point:
        x: -59.7401
        y: -82.3465
        z: 0.00396749
        function: run
    - point:
        x: -53.6025
        y: -76.6368
        z: 0.0039694
        function: run
    - point:
        x: -47.7764
        y: -66.9972
        z: 0.00396177
        function: run
    - point:
        x: -40.7683
        y: -51.0908
        z: 0.00395223
        function: run
    - point:
        x: -36.4295
        y: -41.1952
        z: 0.0039713
        function: run
    - point:
        x: -39.9885
        y: -40.0427
        z: 0.00397512
        function: run
    - point:
        x: -44.7757
        y: -36.2696
        z: 0.0039713
        function: run
    - point:
        x: -45.2562
        y: -28.9136
        z: 0.0039713
        function: run
    - point:
        x: -45.5107
        y: -22.3279
        z: 0.0039713
        function: run
    - point:
        x: -46.84
        y: -19.6546
        z: 0.0039713
        function: run
    - point:
        x: -51.4708
        y: -18.5041
        z: 0.0039713
        function: run
    - point:
        x: -57.1838
        y: -16.1901
        z: 0.0039713
        function: run
    - point:
        x: -64.9225
        y: -12.0709
        z: 0.0039713
        function: run
    - point:
        x: -70.0382
        y: -10.7974
        z: 0.00396749
        function: run
    - point:
        x: -76.1936
        y: -10.5094
        z: 0.00396367
        function: run
    - point:
        x: -83.1856
        y: -8.05002
        z: 0.00396367
        function: run
    - point:
        x: -83.4592
        y: 7.56098
        z: 0.00396558
        function: run
    - point:
        x: -83.8434
        y: 24.7728
        z: 0.00396749
        function: run
    - point:
        x: -83.9333
        y: 34.3167
        z: 0.00396939
        function: run
    - point:
        x: -81.6941
        y: 37.848
        z: 0.00396749
        function: run
    - point:
        x: -81.3998
        y: 41.8698
        z: 0.00396749
        function: run
    - point:
        x: -62.2661
        y: 44.0385
        z: 0.00396939
        function: run
    - point:
        x: -57.732
        y: 40.1274
        z: 0.00396749
        function: run
    - point:
        x: -44.1628
        y: 41.7399
        z: 0.00396176
        function: run
    - point:
        x: -39.8125
        y: 41.2761
        z: 0.00395986
        function: run
    - point:
        x: -33.3256
        y: 38.5149
        z: 0.00395986
        function: run
    - point:
        x: -24.2671
        y: 38.9042
        z: 0.00395986
        function: run
    - point:
        x: -21.2034
        y: 38.2678
        z: 0.00395986
        function: run
    - point:
        x: -19.2041
        y: 34.0626
        z: 0.00395986
        function: run
    - point:
        x: -17.22
        y: 28.8168
        z: 0.00395986
        function: run
    - point:
        x: -18.9739
        y: 18.8417
        z: 0.00395795
        function: run
    - point:
        x: -21.7374
        y: 4.43965
        z: 0.00395032
        function: run
    - point:
        x: -24.5864
        y: -6.4762
        z: 0.00394269
        function: run
    - point:
        x: -28.2245
        y: -18.8729
        z: 0.00393506
        function: run
    - point:
        x: -35.1761
        y: -16.9001
        z: 0.00393506
        function: run
    - point:
        x: -43.0173
        y: -18.4182
        z: 0.00393506
        function: suspend
    - point:
        x: -46.7961
        y: -19.6223
        z: 0.00393506
        function: run
    - point:
        x: -51.4107
        y: -18.4839
        z: 0.00393125
        function: run
    - point:
        x: -57.1688
        y: -16.2129
        z: 0.00393315
        function: run
    - point:
        x: -64.9548
        y: -12.008
        z: 0.00393125
        function: run
    - point:
        x: -70.0772
        y: -10.8347
        z: 0.00392934
        function: run
    - point:
        x: -76.2355
        y: -10.5862
        z: 0.00392743
        function: run
    - point:
        x: -83.2202
        y: -8.08284
        z: 0.00392743
        function: run
    - point:
        x: -84.0868
        y: -15.2088
        z: 0.00392552
        function: run
    - point:
        x: -83.5752
        y: -31.4303
        z: 0.00392552
        function: run
    - point:
        x: -83.3616
        y: -46.3887
        z: 0.00392171
        function: run
    - point:
        x: -82.5368
        y: -53.6289
        z: 0.00392171
        function: run
    - point:
        x: -74.8354
        y: -63.6313
        z: 0.00392171
        function: run
    - point:
        x: -69.4142
        y: -69.6547
        z: 0.00392171
        function: run
    - point:
        x: -70.0445
        y: -75.3895
        z: 0.00392171
        function: run
    - point:
        x: -66.0932
        y: -80.8848
        z: 0.00392171
        function: run
    - point:
        x: -64.5943
        y: -88.0679
        z: 0.0039198
        function: run
    - point:
        x: -76.3278
        y: -88.4067
        z: 0.00391789
        function: change_3
