waypoints:
    - point:
        x: -44.5405
        y: -88.6036
        z: 0.00395604
        function: run
    - point:
        x: -1.84945
        y: -88.9936
        z: 0.00395986
        function: run
    - point:
        x: 38.8146
        y: -88.8745
        z: 0.00397511
        function: run
    - point:
        x: 39.2118
        y: -72.7852
        z: 0.00340227
        function: change_0
