waypoints:
    - point:
        x: 47.5523
        y: -89.1803
        z: 0.00395413
        function: run
    - point:
        x: 26.0238
        y: -88.97
        z: 0.00396368
        function: run
    - point:
        x: 6.23136
        y: -89.0735
        z: 0.0039713
        function: run
    - point:
        x: -2.8282
        y: -88.8277
        z: 0.00340227
        function: run
    - point:
        x: -2.9429
        y: -84.1152
        z: 0.00339846
        function: change_4
