waypoints:
    - point:
        x: -81.7726
        y: -44.179
        z: 0.00396749
        function: run
    - point:
        x: -82.0605
        y: -75.5898
        z: 0.0039694
        function: run
    - point:
        x: -81.7878
        y: -86.1528
        z: 0.00396177
        function: run
    - point:
        x: -73.778
        y: -88.1619
        z: 0.00395223
        function: run
    - point:
        x: -61.232
        y: -88.5223
        z: 0.00396749
        function: run
    - point:
        x: -14.2218
        y: -88.095
        z: 0.00397512
        function: run
    - point:
        x: 38.9753
        y: -87.7119
        z: 0.00397893
        function: run
    - point:
        x: 55.1084
        y: -85.4825
        z: 0.00397512
        function: run
    - point:
        x: 67.7595
        y: -85.4073
        z: 0.00397893
        function: change_0
