waypoints:
    - point:
        x: 45.4663
        y: -31.8265
        z: 0.00395986
        function: run
    - point:
        x: 41.0632
        y: -26.0467
        z: 0.00395986
        function: run
    - point:
        x: 38.4895
        y: -21.7854
        z: 0.00397512
        function: run
    - point:
        x: 32.6054
        y: -16.8403
        z: 0.00396749
        function: run
    - point:
        x: 4.69378
        y: -19.1113
        z: 0.00395986
        function: run
    - point:
        x: -41.0648
        y: -22.9659
        z: 0.00396749
        function: run
    - point:
        x: -74.1947
        y: -26.5283
        z: 0.00396749
        function: run
    - point:
        x: -74.0731
        y: -45.1399
        z: 0.00396368
        function: run
    - point:
        x: -74.1986
        y: -96.5152
        z: 0.00395605
        function: change_2
    - point:
        x: -74.0707
        y: -80.1084
        z: 0.00395605
        function: suspend
