waypoints:
    - point:
        x: -4.44146
        y: -88.611
        z: 0.00396367
        function: run
    - point:
        x: -1.0632
        y: -84.6995
        z: 0.00395986
        function: run
    - point:
        x: -1.06979
        y: -71.4918
        z: 0.0039713
        function: run
    - point:
        x: -6.76417
        y: -71.1391
        z: 0.00340227
        function: run
    - point:
        x: -32.2762
        y: -70.1196
        z: 0.00339846
        function: run
    - point:
        x: -32.5324
        y: -38.2878
        z: 0.00339846
        function: run
    - point:
        x: -33.1908
        y: 1.51056
        z: 0.00339464
        function: run
    - point:
        x: -8.28974
        y: 6.04589
        z: 0.00339083
        function: run
    - point:
        x: 17.5115
        y: 4.92814
        z: 0.00339083
        function: run
    - point:
        x: 16.7542
        y: -22.3446
        z: 0.00338701
        function: run
    - point:
        x: 16.2694
        y: -58.5825
        z: 0.00338701
        function: run
    - point:
        x: 8.59098
        y: -67.7639
        z: 0.00338701
        function: run
    - point:
        x: 2.50892
        y: -71.0943
        z: 0.00339083
        function: run
    - point:
        x: -10.4004
        y: -70.8399
        z: 0.00339083
        function: run
    - point:
        x: -32.1137
        y: -70.1824
        z: 0.00338701
        function: run
    - point:
        x: -32.4341
        y: -47.022
        z: 0.00338701
        function: run
    - point:
        x: -38.7648
        y: -48.0476
        z: 0.0033851
        function: run
    - point:
        x: -53.1314
        y: -47.8658
        z: 0.00338701
        function: run
    - point:
        x: -59.6593
        y: -46.8318
        z: 0.0033832
        function: run
    - point:
        x: -60.3032
        y: -37.9786
        z: 0.0033832
        function: run
    - point:
        x: -61.439
        y: -11.1774
        z: 0.0033832
        function: run
    - point:
        x: -61.2642
        y: -3.96473
        z: 0.00338129
        function: run
    - point:
        x: -52.0391
        y: -3.12287
        z: 0.0033832
        function: run
    - point:
        x: -47.0621
        y: -1.4644
        z: 0.0033851
        function: run
    - point:
        x: -33.3324
        y: -1.30996
        z: 0.00338892
        function: run
    - point:
        x: -32.7102
        y: -18.6766
        z: 0.00339273
        function: run
    - point:
        x: -32.6064
        y: -41.6833
        z: 0.00339273
        function: suspend
    - point:
        x: -32.4208
        y: -47.0397
        z: 0.00339178
        function: run
    - point:
        x: -38.7726
        y: -48.02
        z: 0.00338987
        function: run
    - point:
        x: -53.1333
        y: -47.8927
        z: 0.00339178
        function: run
    - point:
        x: -59.7062
        y: -46.8418
        z: 0.00339178
        function: run
    - point:
        x: -71.6273
        y: -46.7925
        z: 0.00338796
        function: run
    - point:
        x: -76.5744
        y: -46.622
        z: 0.00338606
        function: suspend
    - point:
        x: -81.9132
        y: -46.474
        z: 0.00338701
        function: run
    - point:
        x: -82.7513
        y: -58.7128
        z: 0.00338701
        function: change_5
