waypoints:
    - point:
        x: -93.5832
        y: -63.8476
        z: 0.00395986
        function: run
    - point:
        x: -92.9993
        y: -45.5504
        z: 0.00395604
        function: run
    - point:
        x: -92.7618
        y: -24.3339
        z: 0.00395604
        function: run
    - point:
        x: -93.2669
        y: -2.40552
        z: 0.00396367
        function: run
    - point:
        x: -93.1528
        y: 18.2816
        z: 0.00397512
        function: change_1
