waypoints:
    - point:
        x: -44.5405
        y: -88.6036
        z: 0.00395604
        function: run
    - point:
        x: -1.84945
        y: -88.9936
        z: 0.00395986
        function: run
    - point:
        x: 42.253
        y: -88.1031
        z: 0.0039713
        function: run
    - point:
        x: 43.216
        y: -72.959
        z: 0.00340227
        function: change_2
#way2
    - point:
        x: -91.7057
        y: -68.2069
        z: 0.00395223
        function: run
    - point:
        x: -92.7743
        y: -24.312
        z: 0.00395223
        function: run
    - point:
        x: -93.5438
        y: 21.1688
        z: 0.00396749
        function: change_3
#way3
    - point:
        x: 45.4663
        y: -31.8265
        z: 0.00395986
        function: run
    - point:
        x: 41.0632
        y: -26.0467
        z: 0.00395986
        function: run
    - point:
        x: 38.4895
        y: -21.7854
        z: 0.00397512
        function: run
    - point:
        x: 32.6054
        y: -16.8403
        z: 0.00396749
        function: run
    - point:
        x: 4.69378
        y: -19.1113
        z: 0.00395986
        function: run
    - point:
        x: -41.0648
        y: -22.9659
        z: 0.00396749
        function: run
    - point:
        x: -74.1947
        y: -26.5283
        z: 0.00396749
        function: run
    - point:
        x: -74.0731
        y: -45.1399
        z: 0.00396368
        function: run
    - point:
        x: -74.1986
        y: -96.5152
        z: 0.00395605
        function: run
    - point:
        x: -74.0707
        y: -80.1084
        z: 0.00395605
        function: suspend
#way4
    - point:
        x: -81.7726
        y: -44.179
        z: 0.00396749
        function: run
    - point:
        x: -82.0605
        y: -75.5898
        z: 0.0039694
        function: run
    - point:
        x: -81.7878
        y: -86.1528
        z: 0.00396177
        function: run
    - point:
        x: -73.778
        y: -88.1619
        z: 0.00395223
        function: run
    - point:
        x: -61.232
        y: -88.5223
        z: 0.00396749
        function: run
    - point:
        x: -14.2218
        y: -88.095
        z: 0.00397512
        function: run
    - point:
        x: 38.9753
        y: -87.7119
        z: 0.00397893
        function: run
    - point:
        x: 65.3836
        y: -85.9648
        z: 0.00397893
        function: change_2
#way5
    - point:
        x: -59.7401
        y: -82.3465
        z: 0.00396749
        function: run
    - point:
        x: -53.6025
        y: -76.6368
        z: 0.0039694
        function: run
    - point:
        x: -47.7764
        y: -66.9972
        z: 0.00396177
        function: run
    - point:
        x: -40.7683
        y: -51.0908
        z: 0.00395223
        function: run
    - point:
        x: -36.4295
        y: -41.1952
        z: 0.0039713
        function: run
    - point:
        x: -39.9885
        y: -40.0427
        z: 0.00397512
        function: run
    - point:
        x: -44.7757
        y: -36.2696
        z: 0.0039713
        function: run
    - point:
        x: -45.2562
        y: -28.9136
        z: 0.0039713
        function: run
    - point:
        x: -45.5107
        y: -22.3279
        z: 0.0039713
        function: run
    - point:
        x: -46.84
        y: -19.6546
        z: 0.0039713
        function: run
    - point:
        x: -51.4708
        y: -18.5041
        z: 0.0039713
        function: run
    - point:
        x: -57.1838
        y: -16.1901
        z: 0.0039713
        function: run
    - point:
        x: -64.9225
        y: -12.0709
        z: 0.0039713
        function: run
    - point:
        x: -70.0382
        y: -10.7974
        z: 0.00396749
        function: run
    - point:
        x: -76.1936
        y: -10.5094
        z: 0.00396367
        function: run
    - point:
        x: -83.1856
        y: -8.05002
        z: 0.00396367
        function: run
    - point:
        x: -83.4592
        y: 7.56098
        z: 0.00396558
        function: run
    - point:
        x: -83.8434
        y: 24.7728
        z: 0.00396749
        function: run
    - point:
        x: -83.9333
        y: 34.3167
        z: 0.00396939
        function: run
    - point:
        x: -81.6941
        y: 37.848
        z: 0.00396749
        function: run
    - point:
        x: -81.3998
        y: 41.8698
        z: 0.00396749
        function: run
    - point:
        x: -62.2661
        y: 44.0385
        z: 0.00396939
        function: run
    - point:
        x: -57.732
        y: 40.1274
        z: 0.00396749
        function: run
    - point:
        x: -44.1628
        y: 41.7399
        z: 0.00396176
        function: run
    - point:
        x: -39.8125
        y: 41.2761
        z: 0.00395986
        function: run
    - point:
        x: -33.3256
        y: 38.5149
        z: 0.00395986
        function: run
    - point:
        x: -24.2671
        y: 38.9042
        z: 0.00395986
        function: run
    - point:
        x: -21.2034
        y: 38.2678
        z: 0.00395986
        function: run
    - point:
        x: -19.2041
        y: 34.0626
        z: 0.00395986
        function: run
    - point:
        x: -17.22
        y: 28.8168
        z: 0.00395986
        function: run
    - point:
        x: -18.9739
        y: 18.8417
        z: 0.00395795
        function: run
    - point:
        x: -21.7374
        y: 4.43965
        z: 0.00395032
        function: run
    - point:
        x: -24.5864
        y: -6.4762
        z: 0.00394269
        function: run
    - point:
        x: -28.2245
        y: -18.8729
        z: 0.00393506
        function: run
    - point:
        x: -35.1761
        y: -16.9001
        z: 0.00393506
        function: run
    - point:
        x: -43.0173
        y: -18.4182
        z: 0.00393506
        function: suspend
    - point:
        x: -46.7961
        y: -19.6223
        z: 0.00393506
        function: run
    - point:
        x: -51.4107
        y: -18.4839
        z: 0.00393125
        function: run
    - point:
        x: -57.1688
        y: -16.2129
        z: 0.00393315
        function: run
    - point:
        x: -64.9548
        y: -12.008
        z: 0.00393125
        function: run
    - point:
        x: -70.0772
        y: -10.8347
        z: 0.00392934
        function: run
    - point:
        x: -76.2355
        y: -10.5862
        z: 0.00392743
        function: run
    - point:
        x: -83.2202
        y: -8.08284
        z: 0.00392743
        function: run
    - point:
        x: -84.0868
        y: -15.2088
        z: 0.00392552
        function: run
    - point:
        x: -83.5752
        y: -31.4303
        z: 0.00392552
        function: run
    - point:
        x: -83.3616
        y: -46.3887
        z: 0.00392171
        function: run
    - point:
        x: -82.5368
        y: -53.6289
        z: 0.00392171
        function: run
    - point:
        x: -74.8354
        y: -63.6313
        z: 0.00392171
        function: run
    - point:
        x: -69.4142
        y: -69.6547
        z: 0.00392171
        function: run
    - point:
        x: -70.0445
        y: -75.3895
        z: 0.00392171
        function: run
    - point:
        x: -66.0932
        y: -80.8848
        z: 0.00392171
        function: run
    - point:
        x: -64.5943
        y: -88.0679
        z: 0.0039198
        function: run
    - point:
        x: -76.3278
        y: -88.4067
        z: 0.00391789
        function: change_1
#way6
    - point:
        x: 51.7659
        y: -87.9184
        z: 0.00395604
        function: run
    - point:
        x: 33.1684
        y: -89.0257
        z: 0.00396749
        function: run
    - point:
        x: 6.23136
        y: -89.0735
        z: 0.0039713
        function: run
    - point:
        x: -2.8282
        y: -88.8277
        z: 0.00340227
        function: run
    - point:
        x: -2.9429
        y: -84.1152
        z: 0.00339846
        function: change_4
#way07
    - point:
        x: -4.44146
        y: -88.611
        z: 0.00396367
        function: run
    - point:
        x: -1.0632
        y: -84.6995
        z: 0.00395986
        function: run
    - point:
        x: -1.06979
        y: -71.4918
        z: 0.0039713
        function: run
    - point:
        x: -6.76417
        y: -71.1391
        z: 0.00340227
        function: run
    - point:
        x: -32.2762
        y: -70.1196
        z: 0.00339846
        function: run
    - point:
        x: -32.5324
        y: -38.2878
        z: 0.00339846
        function: run
    - point:
        x: -33.1908
        y: 1.51056
        z: 0.00339464
        function: run
    - point:
        x: -8.28974
        y: 6.04589
        z: 0.00339083
        function: run
    - point:
        x: 17.5115
        y: 4.92814
        z: 0.00339083
        function: run
    - point:
        x: 16.7542
        y: -22.3446
        z: 0.00338701
        function: run
    - point:
        x: 16.2694
        y: -58.5825
        z: 0.00338701
        function: run
    - point:
        x: 8.59098
        y: -67.7639
        z: 0.00338701
        function: run
    - point:
        x: 2.50892
        y: -71.0943
        z: 0.00339083
        function: run
    - point:
        x: -10.4004
        y: -70.8399
        z: 0.00339083
        function: run
    - point:
        x: -32.1137
        y: -70.1824
        z: 0.00338701
        function: run
    - point:
        x: -32.4341
        y: -47.022
        z: 0.00338701
        function: run
    - point:
        x: -38.7648
        y: -48.0476
        z: 0.0033851
        function: run
    - point:
        x: -53.1314
        y: -47.8658
        z: 0.00338701
        function: run
    - point:
        x: -59.6593
        y: -46.8318
        z: 0.0033832
        function: run
    - point:
        x: -60.3032
        y: -37.9786
        z: 0.0033832
        function: run
    - point:
        x: -61.439
        y: -11.1774
        z: 0.0033832
        function: run
    - point:
        x: -61.2642
        y: -3.96473
        z: 0.00338129
        function: run
    - point:
        x: -52.0391
        y: -3.12287
        z: 0.0033832
        function: run
    - point:
        x: -47.0621
        y: -1.4644
        z: 0.0033851
        function: run
    - point:
        x: -33.3324
        y: -1.30996
        z: 0.00338892
        function: run
    - point:
        x: -32.7102
        y: -18.6766
        z: 0.00339273
        function: run
    - point:
        x: -32.6064
        y: -41.6833
        z: 0.00339273
        function: suspend
    - point:
        x: -32.4208
        y: -47.0397
        z: 0.00339178
        function: run
    - point:
        x: -38.7726
        y: -48.02
        z: 0.00338987
        function: run
    - point:
        x: -53.1333
        y: -47.8927
        z: 0.00339178
        function: run
    - point:
        x: -59.7062
        y: -46.8418
        z: 0.00339178
        function: run
    - point:
        x: -71.6273
        y: -46.7925
        z: 0.00338796
        function: run
    - point:
        x: -76.5744
        y: -46.622
        z: 0.00338606
        function: suspend
    - point:
        x: -81.9132
        y: -46.474
        z: 0.00338701
        function: run
    - point:
        x: -82.0385
        y: -50.2095
        z: 0.00338701
        function: change_1
    - point:
        x: -82.1814
        y: -49.3437
        z: 0.00395604
        function: run
    - point:
        x: -80.299
        y: -87.5319
        z: 0.00395223
        function: run
    - point:
        x: -63.4021
        y: -87.8698
        z: 0.00396367
        function: run
    - point:
        x: -45.1032
        y: -88.3972
        z: 0.00339464
        function: run
    - point:
        x: -44.5211
        y: -99.2054
        z: 0.00339464
        function: suspend
#way8
    - point:
        x: -82.1814
        y: -49.3437
        z: 0.00395604
        function: run
    - point:
        x: -80.299
        y: -87.5319
        z: 0.00395223
        function: run
    - point:
        x: -63.4021
        y: -87.8698
        z: 0.00396367
        function: run
    - point:
        x: -45.1032
        y: -88.3972
        z: 0.00339464
        function: run
    - point:
        x: -44.5211
        y: -99.2054
        z: 0.00339464
        function: suspend
